@extends('layouts.app')

@section('title', 'AI Assistant')
@section('body-class', 'min-h-screen bg-slate-100 font-sans text-slate-900')

@section('content')
    <div class="mx-auto flex h-dvh max-w-5xl flex-col overflow-hidden bg-white shadow-xl md:my-6 md:h-[calc(100dvh-3rem)] md:rounded-3xl">
        <header class="flex items-center gap-3 border-b border-slate-200 px-5 py-4 sm:px-8">
            <div class="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-violet-600 text-lg font-bold text-white">
                AI
            </div>
            <div>
                <h1 class="text-lg font-semibold">AI Assistant</h1>
                <p class="text-sm text-slate-500">Gemini decides which MCP tool to call</p>
            </div>
            <span class="ml-auto hidden rounded-full bg-violet-50 px-3 py-1 text-xs font-medium text-violet-700 sm:inline-flex">
                Laravel AI SDK + MCP tools
            </span>
        </header>

        <main id="messages" class="flex-1 space-y-6 overflow-y-auto px-4 py-6 sm:px-8" aria-live="polite">
            <section id="welcome" class="mx-auto mt-12 max-w-lg text-center">
                <div class="mx-auto mb-4 flex size-14 items-center justify-center rounded-2xl bg-violet-50 text-2xl text-violet-600">
                    ✦
                </div>
                <h2 class="text-xl font-semibold">Ask me anything</h2>
                <p class="mt-2 text-sm leading-6 text-slate-500">
                    I can check live weather, rain forecasts, and the sample users. Each tool I use is shown under my reply.
                </p>
                <p class="mt-4 text-xs text-slate-400">Try: “Lahore mein abhi mausam kaisa hai?” or “Kya Zafar naam ka koi user hai?”</p>
            </section>
        </main>

        <form id="chat-form" class="border-t border-slate-200 bg-white px-4 py-4 sm:px-8">
            <label for="message" class="sr-only">Your message</label>
            <div class="flex items-end gap-3 rounded-2xl border border-slate-300 bg-white p-2 shadow-sm transition focus-within:border-violet-400 focus-within:ring-4 focus-within:ring-violet-100">
                <textarea id="message" name="message" rows="1" maxlength="1000" required
                          placeholder="Ask about weather, rain, or the sample users..."
                          class="max-h-32 min-h-11 flex-1 resize-y border-0 bg-transparent px-3 py-2.5 text-sm outline-none placeholder:text-slate-400"
                          aria-describedby="chat-hint"></textarea>
                <button id="send-button" type="submit"
                        class="inline-flex h-11 shrink-0 items-center justify-center rounded-xl bg-violet-600 px-4 text-sm font-medium text-white transition hover:bg-violet-700 focus:outline-none focus:ring-4 focus:ring-violet-200 disabled:cursor-not-allowed disabled:bg-slate-300">
                    Send
                </button>
            </div>
            <p id="chat-hint" class="mt-2 text-center text-xs text-slate-400">
                Replies are generated by Gemini. Press Enter to send; Shift+Enter for a new line.
            </p>
        </form>
    </div>

    <script>
        const endpoint = @json(route('ai-chat.send'));
        const csrfToken = @json(csrf_token());
        const chatForm = document.getElementById('chat-form');
        const messageInput = document.getElementById('message');
        const sendButton = document.getElementById('send-button');
        const messages = document.getElementById('messages');
        const welcome = document.getElementById('welcome');
        const history = [];

        function addMessage(role, text, tools = [], isError = false) {
            const row = document.createElement('article');
            row.className = role === 'user' ? 'flex justify-end' : 'flex justify-start';

            const bubble = document.createElement('div');
            bubble.className = role === 'user'
                ? 'max-w-[85%] whitespace-pre-wrap rounded-2xl rounded-br-md bg-violet-600 px-4 py-3 text-sm leading-6 text-white sm:max-w-[75%]'
                : `max-w-[95%] whitespace-pre-wrap rounded-2xl rounded-bl-md px-4 py-3 text-sm leading-6 sm:max-w-[85%] ${isError ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-800'}`;

            const reply = document.createElement('p');
            reply.textContent = text;
            bubble.append(reply);

            if (tools.length > 0) {
                const toolList = document.createElement('ul');
                toolList.className = 'mt-3 flex flex-wrap gap-2 whitespace-normal';

                for (const tool of tools) {
                    const item = document.createElement('li');
                    item.className = 'rounded-lg border border-violet-200 bg-white px-2 py-1 font-mono text-xs text-violet-700';
                    item.textContent = `${tool.name}(${JSON.stringify(tool.arguments)})`;
                    toolList.append(item);
                }

                bubble.append(toolList);
            }

            row.append(bubble);
            messages.append(row);
            messages.scrollTop = messages.scrollHeight;

            return row;
        }

        async function askAssistant(message) {
            const response = await fetch(endpoint, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': csrfToken,
                },
                body: JSON.stringify({ message, history: history.slice(-20) }),
            });

            const payload = await response.json().catch(() => ({}));

            if (!response.ok) {
                throw new Error(payload.message ?? `The server returned HTTP ${response.status}.`);
            }

            return payload;
        }

        chatForm.addEventListener('submit', async event => {
            event.preventDefault();

            const message = messageInput.value.trim();

            if (!message || sendButton.disabled) {
                return;
            }

            welcome.hidden = true;
            addMessage('user', message);
            messageInput.value = '';
            sendButton.disabled = true;
            sendButton.textContent = '...';
            const status = addMessage('assistant', 'Thinking...');

            try {
                const result = await askAssistant(message);
                status.remove();
                addMessage('assistant', result.reply || '(No reply)', result.tools);

                if (result.reply) {
                    history.push({ role: 'user', content: message }, { role: 'assistant', content: result.reply });
                }
            } catch (error) {
                console.error('AI chat request failed.', error);
                status.remove();
                addMessage('assistant', error.message || 'Could not get a reply. Please try again.', [], true);
            } finally {
                sendButton.disabled = false;
                sendButton.textContent = 'Send';
                messageInput.focus();
            }
        });

        messageInput.addEventListener('keydown', event => {
            if (event.key === 'Enter' && !event.shiftKey) {
                event.preventDefault();
                chatForm.requestSubmit();
            }
        });
    </script>
@endsection
